name: generate animation

on:
  schedule:
    - cron: "* */12 * * *" # roda a cada 12 horas
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate-pacman-graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Einer-Sulivan
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-light&color_snake=#f3df13
            dist/pacman-contribution-graph-dark.svg?palette=github-dark&color_snake=#f3df13

      - name: push pacman-contribution-graph to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
